name: 'Typo Check'
on:   
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:  
      - name: typos-action
        uses: crate-ci/typos@v1.16.23
